### ISSUE TITLE
Sharing iP code quality feedback [for @desmondyst]

### ISSUE THREAD

**Issue by soc-se-bot-red** [desmondyst/ip#4]
@desmondyst We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/duke/Duke.java` lines `38-43`](https://github.com/desmondyst/ip/blob/37447f3ba4a497abfb0ed7ec85e77aeed5c34e29/src/main/java/duke/Duke.java#L38..L43):

```java

    /**
     * Perform an execution based on the command and return the corresponding response.
     *
     * @param userInput The input by the user.
     * @return The corresponding response to the command.
     */

```

Example from [`src/main/java/duke/task/Task.java` lines `39-41`](https://github.com/desmondyst/ip/blob/37447f3ba4a497abfb0ed7ec85e77aeed5c34e29/src/main/java/duke/task/Task.java#L39..L41):

```java

    /**
     * Mark the Task as done.
     */

```

Example from [`src/main/java/duke/task/Task.java` lines `46-48`](https://github.com/desmondyst/ip/blob/37447f3ba4a497abfb0ed7ec85e77aeed5c34e29/src/main/java/duke/task/Task.java#L46..L48):

```java

    /**
     * Mark the Task as undone.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message (Subject Only)

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by desmondyst** [comment]
Fixed in Add user guide commit.
